[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cpi_invoke = "55xRZZnhSk1aN6seNTj75mThJEjZkBRYPQJ8qvKVh1eC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
